GET http://localhost:5297/games

###
GET http://localhost:5297/games/2

###
POST http://localhost:5297/games
Content-Type: application/json

{
    "Name":"Call Of Duty",
    "GenreId":1,
    "Price":10.2,
    "ReleaseDate": "2008-10-18"
}

###
PUT http://localhost:5297/games/2
Content-Type: application/json

{
    "name": "Genshin Impact",
    "genreId": 5,
    "price": 20,
    "releaseDate": "2011-10-18"
}

###
DELETE  http://localhost:5297/games/4

//for Genres

###
GET http://localhost:5297/genres